### PR TITLE
Fix copying specific version of secrets

### LINKED ISSUE #222: Safe panics when trying to copy from a specific version
When using a KV2 backend trying to copy from a specific version causes safe to panic.

```bash
./safe cp secret/test^3 secret/hmm
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/starkandwayne/safe/vault.(*Vault).Copy(0xc000061d00, 0x7ffeefbff4e2, 0xd, 0xc0002a3d50, 0xc, 0x0, 0x2, 0xc000155e58)
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/vault/vault.go:663 +0xa2f
main.main.func32(0x13b57ec, 0x4, 0xc000384bc0, 0x2, 0x2, 0xc000372601, 0x0)
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/main.go:2706 +0x2fc
main.(*Runner).Execute(0xc000060ff0, 0x13b57ec, 0x4, 0xc000384bc0, 0x2, 0x2, 0x0, 0x0)
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/runner.go:117 +0x9b
main.main()
	/Users/dks0579496/go/src/github.com/starkandwayne/safe/main.go:4161 +0x2895
```

### PR DESCRIPTION
**Pull request by daviddob**
Fixes panic when trying to copy specific versions of secrets.
Properly errors when trying to Deep copy of specific secrets or copy a secret to a destination version
Closes #222

### CODE REVIEW

File: vault/vault.go [hunk 1]
```diff
@@ -612,8 +612,16 @@ func (v *Vault) Copy(oldpath, newpath string, opts MoveCopyOpts) error {
...
+	srcPath, srcKey, srcVersion := ParsePath(oldpath)
+	dstPath, dstKey, dstVersion := ParsePath(newpath)
+
+	if dstVersion != 0 {
+		return fmt.Errorf("Copying a secret to a specific destination version is not supported")
+	}
+
+	if opts.Deep && srcVersion != 0 {
+		return fmt.Errorf("Performing a deep copy of a specified version is not supported")
+	}
```
Comment (thomasmitchell) [inline vault/vault.go:625]: extra constraint, recursion and a specific version doesn't make much sense either

File: vault/vault.go [hunk 2]
```diff
@@ -651,15 +659,30 @@ func (v *Vault) Copy(oldpath, newpath string, opts MoveCopyOpts) error {
...
+			AllowDeletedSecrets: opts.Deep || srcVersion != 0,
 		})
 
 		if err != nil {
 			return err
 		}
 
+		if len(t) == 0 {
+			// Prevent a panic
+			return fmt.Errorf("No valid secrets were found to be copied")
```
Comment (thomasmitchell) [inline vault/vault.go:673]: this error should probably be normalized to whatever the normal not found is, something like `no secret was found at path 'blah'`

**Review by thomasmitchell — CHANGES_REQUESTED** [review]

File: main.go [hunk 3]
```diff
@@ -2687,6 +2687,10 @@ and overwrite all versions of the secret at the destination.
 			}
 		}
 
+		if opt.Copy.Recurse && (vault.PathHasVersion(args[0]) || vault.PathHasVersion(args[1])) {
```
Comment (thomasmitchell) [inline main.go:2690]: this reminds me that the destination path shouldn't support a version at all.

**Review by thomasmitchell — CHANGES_REQUESTED** [review]

**Comment by thomasmitchell** [comment]
I like this.
