### PR TITLE
Overhaul Command-line Handling

### LINKED ISSUE #70: getopt handling in chained commands is b0rked
there is a bug in the latest safe version that let genesis crash

 ```safe gen ${VAULT_PREFIX}/creds/users/admin password -- \
   gen ${VAULT_PREFIX}/creds/cc bulk_api -- \
   gen ${VAULT_PREFIX}/creds/cc internal_api -- \
   gen ${VAULT_PREFIX}/creds/cc staging_upload -- \
   gen ${VAULT_PREFIX}/creds/cc db_encryption_key -- \
   gen ${VAULT_PREFIX}/creds/consul encryption_key -- \
   gen ${VAULT_PREFIX}/creds/gorouter route_svcs_secret -- \
   gen ${VAULT_PREFIX}/creds/gorouter status_api_pass -- \
   gen ${VAULT_PREFIX}/creds/loggregator endpoint_secret -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets admin_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_broker -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_routing -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_user_lookup -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets doppler -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets firehose -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets gorouter -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets login -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets notifications -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets ssh_proxy -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets tcp_emitter -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets tcp_router -- \
   gen ${VAULT_PREFIX}/creds/nats password -- \
   gen ${VAULT_PREFIX}/creds/blobstore webdav_password -- \
   gen ${VAULT_PREFIX}/creds/blobstore secret -- \
   gen ${VAULT_PREFIX}/creds/diego encryption_key -- \
   gen ${VAULT_PREFIX}/creds/diego secret -- \
   gen ${VAULT_PREFIX}/creds/db uaaadmin -- \
   gen ${VAULT_PREFIX}/creds/db ccadmin -- \
   gen ${VAULT_PREFIX}/creds/db diegoadmin -- \
   gen ${VAULT_PREFIX}/uaadb password -- \
   gen ${VAULT_PREFIX}/ccdb password -- \
   gen ${VAULT_PREFIX}/diegodb password -- \
   gen ${VAULT_PREFIX}/routingdb password -- \
   >/dev/null
Generating secrets
/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/safe/vendor/github.com/pborman/getopt/string.go:52: --policy already declared at /tmp/build/01f561ac/gopath/src/github.com/starkandwayne/safe/vendor/github.com/pborman/getopt/string.go:52%
```
this piece of code in .env_hooks/setup_cf_secrets

the error exists since 0.0.30

### PR DESCRIPTION
**Pull request by jhunt**
Drop getopt in favor of a more flexible underlying library that natively
supports chained command execution with sub-flags and all the niceties
operators expect.

Every care has been taken to maintain existing calling conventions and
preserve established semantics.  The following changes go against that:

  - `gen` regained it's `--policy` argument; this was the change (#44)
    that brought #70 to our attention in the first place.
  - Commands that failed their recursive force check (copy, move,
    delete) would cause an entire chain of sub-commands to fail.  Now,
    only the affected sub-command is affected, and subsequent
    sub-commands will be executed.

This new CLI library is much more foregiving about sub-command flags.
It also allows global options to appear anywhere inside the command
line, allowing operators to tack a `-k` onto the end of a failing login
command, without too much fuss.

Primarily, this change fixes #70.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -533,7 +628,7 @@ certificate validation failure, etc. occur, they will be printed as well.
 		}
 		os.Exit(0)
 		return nil
-	}, "check")
```
Comment (geofffranks) [inline main.go]: Was this alias dropped on purpose?

Comment (jhunt) [inline main.go]: Oops.
